version: '2'

services:
  redis:
    image: redis:7
    ports:
      - "6382:6379"

  composer-aux:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs --no-scripts

  myapp:
    image: bitnami/laravel:latest
    user: root
    ports:
      - "8084:8000"
    environment:
      DB_HOST: 192.168.111.8
      DB_PORT: 3306
      DB_USERNAME: db_cmit
      DB_DATABASE: db_cmit
      DB_PASSWORD: db_cmit
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/opt/bitnami/laravel
    depends_on:
      - redis
      - composer-aux
